const DB_DEFATUL_TYPE = 'DB_DEFATUL_TYPE'
const STATUS_CREATED = 'CREATED'
const STATUS_FINISHED = 'FINISHED'
const STATUS_FAIL = 'FAIL'

module.exports = {
    DB_DEFATUL_TYPE,
    STATUS_CREATED,
    STATUS_FINISHED,
    STATUS_FAIL
}